name: Scraper

on:
  schedule:
    # Run once per day at midnight Pacific Time (08:00 UTC)
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 🏃 Run scraper script
        run: python bodyspec_appointment_table.py
